### ISSUE TITLE
When merge the data of CustomerMedicalConditions, did you find redundant lines appear?

### ISSUE THREAD

**Issue by ZHANG-Chenyuan1** [YUSIZOU11/Group-5#5]
Our team plans to analyze the data from 2018 to 2021 separately according to several key nodes of the epidemic, and I am responsible for processing and analyzing the data before the epidemic.
Before analyzing the data, I have to clean the dataframe. 

Followings are the cleaning tips:
1）Remove ones who are not 'User'.
2) Remove ones without 'ExternalID' and 'DateOfBirth'.
3) Remove ones who are under 18 years old.
4) Remove useless and distracting information.
5) Merge the data to make them look simplify.

When I merge the data of 'CC _data' with 'CustomerMedicalConditions' ,there are redundant lines appearing?
![4241638265475_ pic](https://user-images.githubusercontent.com/95237074/144023836-868ca1d6-69b6-43d2-8d50-2935b3e0a712.jpg)

**Comment by yangl17** [comment]
Basically agree.
# First non-users need to be cleaned up
data1_ = data1[data1['Role'] == 'User']#Only user data is retained
data1_.dropna(subset=['ExternalID'],inplace=True)
data1_.index = range(data1_.shape[0])

Lines with 'ExternalID 'being blank are difficult to use, which can affect the code's accuracy to some extent.

# When analyzing certain data, I think duplicate rows also need to be cleaned.
Here we use the following function:
new_data= data1_.drop_duplicates(subset=['VisitorID'],keep='last',inplace=False)
