### ISSUE TITLE
#issue Duplicate values in 'CustomerMedicalConditions04Nov21.xlsx'

### ISSUE THREAD

**Issue by HN-W** [YUSIZOU11/Group-5#6]
I found that there are duplicate values in the EXTERNAL ID, if we want to de-duplicate them should we keep the first or the last one? If we want to count the condition, will the removed values affect the result?
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/95534896/144722788-0877d2ec-9dc7-4010-b62d-6a25089f4fed.png)

**Comment by yangl17** [comment]
I think it depends on what problem you're trying to solve. If we want the user address, we should keep the last one. Because users are likely to change addresses over time. So using the last one is the most accurate.

**Comment by DICKJIA** [comment]
I think the main reason for a duplicate is 'StaffPlanConditions', the other value is all the same. So, if we need to analyze 'StaffPlanConditions', we cannot de-duplicate. But if we want to analyze data without 'StaffPlanConditions', we absolutely need to de-duplicate it.

**Comment by ZHANG-Chenyuan1** [comment]
I also think the reason of duplicate value is 'StaffPlanConditions', you can consider whether you need to remove duplicate values based on the data you need for the chart you are making.
