### ISSUE TITLE
The normal distribution problem

### ISSUE THREAD

**Issue by yangl17** [YUSIZOU11/Group-5#8]
I want to know if you think this is a standard normal distribution? Maybe it's a skewed distribution.
<img width="1118" alt="截屏2021-12-04 21 11 17" src="https://user-images.githubusercontent.com/95534806/144724748-19aaaeae-c410-444b-9132-b88300e5c249.png">

**Comment by DICKJIA** [comment]
I think it is normal distribution but a little bit left skewed.

**Comment by HN-W** [comment]
I think it is a asymmetrical distribution, looked like a bit negative direction

**Comment by ZHANG-Chenyuan1** [comment]
I have drawed a same plot as yours, I think it is just a standard normal distribution.
